Fix test action (#12)
* chore(deps)!: update all dependencies

Tests keep dying to some obscure error,
seemingly flake8 + something else uses
a deprecated API or such.

Maybe this fixes the issue.

* chore(deps)!: update pre-commit deps

Seems like the tests action failed here
instead of in actual deps.
Not sure why tests action run pre-commit
though. Bit by bit.. :)

* chore(deps)!: deprecated flakehell->flakeheaven

* test: ignore ANN401 for nox

nox doesn't provide full types through
the call stack so ignore instead.

* test: deprecated --constraints->-r

nox > Running session mypy-3.10
nox > Creating virtual environment (virtualenv) using python3.10 in .nox/mypy-3-10
nox > python -m pip install .
nox > poetry export --dev --without-hashes --format=requirements.txt --output=/tmp/tmpgp_y8nnn
The `--dev` option is deprecated, use the `--with dev` notation instead.
nox > python -m pip install --constraint=/tmp/tmpgp_y8nnn invoke mypy
nox > Command python -m pip install --constraint=/tmp/tmpgp_y8nnn invoke mypy failed with exit code 1:
DEPRECATION: Constraints are only allowed to take the form of a package name and a version specifier. Other forms were originally permitted as an accident of the implementation, but were undocumented. The new implementation of the resolver no longer supports these forms. A possible replacement is replacing the constraint with a requirement. Discussion can be found at https://github.com/pypa/pip/issues/8210
ERROR: Constraints cannot have extras
nox > Session mypy-3.10 failed.
Error: Process completed with exit code 1.

* tests: use nox_poetry

pip --constaint doesn't handle extras
use poetry completely instead

* tests: add nox_poetry to mypy.ini